### ISSUE TITLE
Rename "processor" to something more appropriate

### ISSUE THREAD

**Issue by paulbatum** [Azure-Samples/functions-quickstart-dotnet-azd#6]
It looks like this sample uses terminology that was copied over from somewhere else - it doesn't seem natural that the bicep module that deploys a simple HTTP triggered function app would be called a "processor"
https://github.com/Azure-Samples/functions-quickstart-dotnet-azd/blob/main/infra/app/processor.bicep

Maybe "api" or "application" or "functionapp"  would be better?

**Comment by paulbatum** [comment]
Other functions quickstarts under Azure-Samples might have the same issue, I didn't check.

**Comment by paulyuk** [comment]
This mirrors what the most popular AI samples do because it's your processor backend.

I do understand the feedback and I like "api" as next best, considering these will pair with other "apps" like front end web apps.
